# Exercise 20
### Task 20.6

In [24]:
import numpy as np

data = np.array([20, 23, -100, -5, 30, 70, -18, 99, 81, 16, 45, 90, -39, -82, 75, 0, 16, 91, 48, 0, 70])

1. Pomocí funkce where v knihovně NumPy vyberte jen záporná čísla.

In [25]:
result1 = np.where(data < 0)
print(data[result1])

[-100   -5  -18  -39  -82]


2. Pomocí funkce where v knihovně NumPy vynerta jen čísla v rozsahu -10 až -1.  (Nápověda: použijte kulaté závorky a znak &)

In [26]:
result2 = np.where((data >= -10) & (data <= -1))
print(data[result2])

[-5]


3. Pomocí funkce where v knihovně NumPy vynerta jen čísla v rozsahu 1 až 50, nebo čísla záporná. (Nápověda: použijte kulaté závorky a znak |)

In [27]:
result3 = np.where((data >= 1) & (data <= 50) | (data < 0))
print(data[result3])

[  20   23 -100   -5   30  -18   16   45  -39  -82   16   48]


### Task 20.7
Pomocí knihovny NumPy a modulu random (pozor, abyste nepoužili místo numpy.random starou dobrou random knihovnu). Vygenerujte náhodná čísla dle následující kritérií

a) Vygenerujte jedno náhodné celé číslo

In [28]:
np.random.randint(1, 100)

23


b) Vygenerujte jedno náhodné desetinné číslo

In [29]:
np.random.rand()

0.4412143452421132

c) Vygenerujte jednorozměrné pole náhodných čísel o velikosti 100 prvků. (Nápověda: použijte parametr size)


In [30]:
np.random.rand(100)

array([0.09363977, 0.44824119, 0.14458582, 0.19831172, 0.584026  ,
       0.43054273, 0.28892039, 0.38435214, 0.15195295, 0.23354674,
       0.29617791, 0.24584378, 0.76074711, 0.06018933, 0.94584707,
       0.07930668, 0.52702375, 0.68026734, 0.51937521, 0.48839818,
       0.19724098, 0.63018393, 0.4955711 , 0.72238956, 0.98796941,
       0.38266673, 0.26786301, 0.23171169, 0.77618548, 0.17704364,
       0.84625507, 0.30869349, 0.87716965, 0.10061081, 0.56927899,
       0.34098879, 0.17467357, 0.28593988, 0.55039351, 0.45237778,
       0.17871059, 0.74800341, 0.12572786, 0.44005564, 0.10337297,
       0.52239557, 0.32394561, 0.72557928, 0.54613228, 0.09417326,
       0.16213234, 0.91292585, 0.11647076, 0.43658356, 0.68698986,
       0.21984935, 0.51905103, 0.12356423, 0.18154993, 0.64129147,
       0.06227791, 0.58249542, 0.14475591, 0.26613052, 0.80459196,
       0.8619327 , 0.25781129, 0.13066873, 0.99594702, 0.80519466,
       0.48354369, 0.44132809, 0.32921589, 0.46744671, 0.33698

d) Vygenerujte matici náhodných čísel o velikosti 10x10 prvků. (Nápověda: použijte parametr size u metod rand(), nebo randint())


In [31]:
np.random.rand(10, 10)

array([[0.62067673, 0.79202623, 0.73497762, 0.63606068, 0.00937078,
        0.56840555, 0.45897386, 0.51863062, 0.36513226, 0.17526575],
       [0.7053594 , 0.1902847 , 0.64418758, 0.07145477, 0.90569176,
        0.11862291, 0.92262241, 0.83313075, 0.79604192, 0.92665729],
       [0.92388263, 0.84208037, 0.6578927 , 0.95581647, 0.756017  ,
        0.17871838, 0.40022371, 0.85004784, 0.97021489, 0.93524461],
       [0.46674214, 0.63106136, 0.73352594, 0.13925837, 0.95916862,
        0.94932459, 0.38026491, 0.61951503, 0.19956946, 0.75758767],
       [0.48515822, 0.74645158, 0.93274048, 0.21003709, 0.60192851,
        0.43947287, 0.6290724 , 0.40975246, 0.00264444, 0.51978723],
       [0.64576455, 0.19196933, 0.53319042, 0.60832783, 0.93798206,
        0.42301454, 0.49850705, 0.00189464, 0.90463843, 0.22142244],
       [0.11734502, 0.61697631, 0.01866721, 0.871333  , 0.0942602 ,
        0.55365667, 0.5112371 , 0.70302751, 0.94542462, 0.97840811],
       [0.13476641, 0.36405284, 0.2771701

e) Vygenerujte náhodnou hodnotu z pole [21,22,34,56]. (Nápověda: použijte metodu choice() )

In [32]:
np.random.choice([21, 22, 34, 56])

34

### Task 20.8

In [33]:
import numpy as np
znamky = [1, 2, 3, 4, 5]
p = np.array([0.1, 0.25, 0.25, 0.28, 0.12])
vygenerovane_znamky = np.random.choice(znamky, size=15, p=p)
print("Vygenerované známky:", vygenerovane_znamky)


Vygenerované známky: [4 2 4 3 3 3 4 5 3 4 3 4 2 3 3]
